package com.aitaskmanager.repository.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   AI利用回数（月次集計）
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ai_usage
 */
public class AiUsage {
    /**
     * Database Column Remarks:
     *   AI利用回数SID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_usage.ai_usage_sid
     *
     * @mbg.generated
     */
    private Integer aiUsageSid;

    /**
     * Database Column Remarks:
     *   ユーザーSID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_usage.user_sid
     *
     * @mbg.generated
     */
    private Integer userSid;

    /**
     * Database Column Remarks:
     *   対象年（西暦）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_usage.year
     *
     * @mbg.generated
     */
    private Integer year;

    /**
     * Database Column Remarks:
     *   対象月（1-12）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_usage.month
     *
     * @mbg.generated
     */
    private Integer month;

    /**
     * Database Column Remarks:
     *   当該年月におけるAI利用回数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_usage.used_count
     *
     * @mbg.generated
     */
    private Integer usedCount;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_usage.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ai_usage.ai_usage_sid
     *
     * @return the value of ai_usage.ai_usage_sid
     *
     * @mbg.generated
     */
    public Integer getAiUsageSid() {
        return aiUsageSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ai_usage.ai_usage_sid
     *
     * @param aiUsageSid the value for ai_usage.ai_usage_sid
     *
     * @mbg.generated
     */
    public void setAiUsageSid(Integer aiUsageSid) {
        this.aiUsageSid = aiUsageSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ai_usage.user_sid
     *
     * @return the value of ai_usage.user_sid
     *
     * @mbg.generated
     */
    public Integer getUserSid() {
        return userSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ai_usage.user_sid
     *
     * @param userSid the value for ai_usage.user_sid
     *
     * @mbg.generated
     */
    public void setUserSid(Integer userSid) {
        this.userSid = userSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ai_usage.year
     *
     * @return the value of ai_usage.year
     *
     * @mbg.generated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ai_usage.year
     *
     * @param year the value for ai_usage.year
     *
     * @mbg.generated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ai_usage.month
     *
     * @return the value of ai_usage.month
     *
     * @mbg.generated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ai_usage.month
     *
     * @param month the value for ai_usage.month
     *
     * @mbg.generated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ai_usage.used_count
     *
     * @return the value of ai_usage.used_count
     *
     * @mbg.generated
     */
    public Integer getUsedCount() {
        return usedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ai_usage.used_count
     *
     * @param usedCount the value for ai_usage.used_count
     *
     * @mbg.generated
     */
    public void setUsedCount(Integer usedCount) {
        this.usedCount = usedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ai_usage.updated_at
     *
     * @return the value of ai_usage.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ai_usage.updated_at
     *
     * @param updatedAt the value for ai_usage.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}