package com.aitaskmanager.repository.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   クレジットパック（買い切りの追加回数）テーブル
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table credit_packs
 */
public class CreditPacks {
    /**
     * Database Column Remarks:
     *   クレジットパックSID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.credit_pack_sid
     *
     * @mbg.generated
     */
    private Integer creditPackSid;

    /**
     * Database Column Remarks:
     *   管理用コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   表示名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   説明文
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   追加回数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.amount
     *
     * @mbg.generated
     */
    private Integer amount;

    /**
     * Database Column Remarks:
     *   価格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.display_price
     *
     * @mbg.generated
     */
    private Integer displayPrice;

    /**
     * Database Column Remarks:
     *   Stripe Price ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.stripe_price_id
     *
     * @mbg.generated
     */
    private String stripePriceId;

    /**
     * Database Column Remarks:
     *   公開フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.enabled
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     * Database Column Remarks:
     *   並び順
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.sort_order
     *
     * @mbg.generated
     */
    private Integer sortOrder;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_packs.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.credit_pack_sid
     *
     * @return the value of credit_packs.credit_pack_sid
     *
     * @mbg.generated
     */
    public Integer getCreditPackSid() {
        return creditPackSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.credit_pack_sid
     *
     * @param creditPackSid the value for credit_packs.credit_pack_sid
     *
     * @mbg.generated
     */
    public void setCreditPackSid(Integer creditPackSid) {
        this.creditPackSid = creditPackSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.code
     *
     * @return the value of credit_packs.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.code
     *
     * @param code the value for credit_packs.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.name
     *
     * @return the value of credit_packs.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.name
     *
     * @param name the value for credit_packs.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.description
     *
     * @return the value of credit_packs.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.description
     *
     * @param description the value for credit_packs.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.amount
     *
     * @return the value of credit_packs.amount
     *
     * @mbg.generated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.amount
     *
     * @param amount the value for credit_packs.amount
     *
     * @mbg.generated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.display_price
     *
     * @return the value of credit_packs.display_price
     *
     * @mbg.generated
     */
    public Integer getDisplayPrice() {
        return displayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.display_price
     *
     * @param displayPrice the value for credit_packs.display_price
     *
     * @mbg.generated
     */
    public void setDisplayPrice(Integer displayPrice) {
        this.displayPrice = displayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.stripe_price_id
     *
     * @return the value of credit_packs.stripe_price_id
     *
     * @mbg.generated
     */
    public String getStripePriceId() {
        return stripePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.stripe_price_id
     *
     * @param stripePriceId the value for credit_packs.stripe_price_id
     *
     * @mbg.generated
     */
    public void setStripePriceId(String stripePriceId) {
        this.stripePriceId = stripePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.enabled
     *
     * @return the value of credit_packs.enabled
     *
     * @mbg.generated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.enabled
     *
     * @param enabled the value for credit_packs.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.sort_order
     *
     * @return the value of credit_packs.sort_order
     *
     * @mbg.generated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.sort_order
     *
     * @param sortOrder the value for credit_packs.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_packs.created_at
     *
     * @return the value of credit_packs.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_packs.created_at
     *
     * @param createdAt the value for credit_packs.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}