package com.aitaskmanager.repository.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   決済履歴
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table payments
 */
public class Payments {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   価格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   通貨
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     * Database Column Remarks:
     *   支払方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.payment_method
     *
     * @mbg.generated
     */
    private String paymentMethod;

    /**
     * Database Column Remarks:
     *   取引ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.payment_id
     *
     * @mbg.generated
     */
    private String paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   支払時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.paid_at
     *
     * @mbg.generated
     */
    private Date paidAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.id
     *
     * @return the value of payments.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.id
     *
     * @param id the value for payments.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.user_id
     *
     * @return the value of payments.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.user_id
     *
     * @param userId the value for payments.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.amount
     *
     * @return the value of payments.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.amount
     *
     * @param amount the value for payments.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.currency
     *
     * @return the value of payments.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.currency
     *
     * @param currency the value for payments.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.payment_method
     *
     * @return the value of payments.payment_method
     *
     * @mbg.generated
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.payment_method
     *
     * @param paymentMethod the value for payments.payment_method
     *
     * @mbg.generated
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.payment_id
     *
     * @return the value of payments.payment_id
     *
     * @mbg.generated
     */
    public String getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.payment_id
     *
     * @param paymentId the value for payments.payment_id
     *
     * @mbg.generated
     */
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.status
     *
     * @return the value of payments.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.status
     *
     * @param status the value for payments.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.paid_at
     *
     * @return the value of payments.paid_at
     *
     * @mbg.generated
     */
    public Date getPaidAt() {
        return paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.paid_at
     *
     * @param paidAt the value for payments.paid_at
     *
     * @mbg.generated
     */
    public void setPaidAt(Date paidAt) {
        this.paidAt = paidAt;
    }
}