package com.aitaskmanager.repository.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   認証管理
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table refresh_tokens
 */
public class RefreshTokens {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   トークン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * Database Column Remarks:
     *   有効期限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.expires_at
     *
     * @mbg.generated
     */
    private Date expiresAt;

    /**
     * Database Column Remarks:
     *   登録時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.id
     *
     * @return the value of refresh_tokens.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.id
     *
     * @param id the value for refresh_tokens.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.user_id
     *
     * @return the value of refresh_tokens.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.user_id
     *
     * @param userId the value for refresh_tokens.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.token
     *
     * @return the value of refresh_tokens.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.token
     *
     * @param token the value for refresh_tokens.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.expires_at
     *
     * @return the value of refresh_tokens.expires_at
     *
     * @mbg.generated
     */
    public Date getExpiresAt() {
        return expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.expires_at
     *
     * @param expiresAt the value for refresh_tokens.expires_at
     *
     * @mbg.generated
     */
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.created_at
     *
     * @return the value of refresh_tokens.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.created_at
     *
     * @param createdAt the value for refresh_tokens.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}