package com.aitaskmanager.repository.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   認証管理
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table refresh_tokens
 */
public class RefreshTokens {
    /**
     * Database Column Remarks:
     *   認証管理SID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.refresh_token_sid
     *
     * @mbg.generated
     */
    private Integer refreshTokenSid;

    /**
     * Database Column Remarks:
     *   ユーザSID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.user_sid
     *
     * @mbg.generated
     */
    private Integer userSid;

    /**
     * Database Column Remarks:
     *   トークン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * Database Column Remarks:
     *   有効期限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.expires_at
     *
     * @mbg.generated
     */
    private Date expiresAt;

    /**
     * Database Column Remarks:
     *   登録時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refresh_tokens.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.refresh_token_sid
     *
     * @return the value of refresh_tokens.refresh_token_sid
     *
     * @mbg.generated
     */
    public Integer getRefreshTokenSid() {
        return refreshTokenSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.refresh_token_sid
     *
     * @param refreshTokenSid the value for refresh_tokens.refresh_token_sid
     *
     * @mbg.generated
     */
    public void setRefreshTokenSid(Integer refreshTokenSid) {
        this.refreshTokenSid = refreshTokenSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.user_sid
     *
     * @return the value of refresh_tokens.user_sid
     *
     * @mbg.generated
     */
    public Integer getUserSid() {
        return userSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.user_sid
     *
     * @param userSid the value for refresh_tokens.user_sid
     *
     * @mbg.generated
     */
    public void setUserSid(Integer userSid) {
        this.userSid = userSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.token
     *
     * @return the value of refresh_tokens.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.token
     *
     * @param token the value for refresh_tokens.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.expires_at
     *
     * @return the value of refresh_tokens.expires_at
     *
     * @mbg.generated
     */
    public Date getExpiresAt() {
        return expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.expires_at
     *
     * @param expiresAt the value for refresh_tokens.expires_at
     *
     * @mbg.generated
     */
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refresh_tokens.created_at
     *
     * @return the value of refresh_tokens.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refresh_tokens.created_at
     *
     * @param createdAt the value for refresh_tokens.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}