package com.aitaskmanager.repository.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   料金プラン
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table subscription_plans
 */
public class SubscriptionPlans {
    /**
     * Database Column Remarks:
     *   料金プランSID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.subscription_plan_sid
     *
     * @mbg.generated
     */
    private Integer subscriptionPlanSid;

    /**
     * Database Column Remarks:
     *   名前
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   月額料金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.price_monthly
     *
     * @mbg.generated
     */
    private BigDecimal priceMonthly;

    /**
     * Database Column Remarks:
     *   月間AI実行上限（null=無制限、0=AI不可）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.ai_quota
     *
     * @mbg.generated
     */
    private Integer aiQuota;

    /**
     * Database Column Remarks:
     *   Stripe Price ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.stripe_price_id
     *
     * @mbg.generated
     */
    private String stripePriceId;

    /**
     * Database Column Remarks:
     *   説明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   有効フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.is_active
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     * Database Column Remarks:
     *   登録時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.subscription_plan_sid
     *
     * @return the value of subscription_plans.subscription_plan_sid
     *
     * @mbg.generated
     */
    public Integer getSubscriptionPlanSid() {
        return subscriptionPlanSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.subscription_plan_sid
     *
     * @param subscriptionPlanSid the value for subscription_plans.subscription_plan_sid
     *
     * @mbg.generated
     */
    public void setSubscriptionPlanSid(Integer subscriptionPlanSid) {
        this.subscriptionPlanSid = subscriptionPlanSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.name
     *
     * @return the value of subscription_plans.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.name
     *
     * @param name the value for subscription_plans.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.price_monthly
     *
     * @return the value of subscription_plans.price_monthly
     *
     * @mbg.generated
     */
    public BigDecimal getPriceMonthly() {
        return priceMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.price_monthly
     *
     * @param priceMonthly the value for subscription_plans.price_monthly
     *
     * @mbg.generated
     */
    public void setPriceMonthly(BigDecimal priceMonthly) {
        this.priceMonthly = priceMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.ai_quota
     *
     * @return the value of subscription_plans.ai_quota
     *
     * @mbg.generated
     */
    public Integer getAiQuota() {
        return aiQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.ai_quota
     *
     * @param aiQuota the value for subscription_plans.ai_quota
     *
     * @mbg.generated
     */
    public void setAiQuota(Integer aiQuota) {
        this.aiQuota = aiQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.stripe_price_id
     *
     * @return the value of subscription_plans.stripe_price_id
     *
     * @mbg.generated
     */
    public String getStripePriceId() {
        return stripePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.stripe_price_id
     *
     * @param stripePriceId the value for subscription_plans.stripe_price_id
     *
     * @mbg.generated
     */
    public void setStripePriceId(String stripePriceId) {
        this.stripePriceId = stripePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.description
     *
     * @return the value of subscription_plans.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.description
     *
     * @param description the value for subscription_plans.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.is_active
     *
     * @return the value of subscription_plans.is_active
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.is_active
     *
     * @param isActive the value for subscription_plans.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.created_at
     *
     * @return the value of subscription_plans.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.created_at
     *
     * @param createdAt the value for subscription_plans.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}