package com.aitaskmanager.repository.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   料金プラン
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table subscription_plans
 */
public class SubscriptionPlans {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   名前
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   支払月
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.price_monthly
     *
     * @mbg.generated
     */
    private BigDecimal priceMonthly;

    /**
     * Database Column Remarks:
     *   登録可能タスク数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.task_limit
     *
     * @mbg.generated
     */
    private Integer taskLimit;

    /**
     * Database Column Remarks:
     *   説明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   登録時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_plans.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.id
     *
     * @return the value of subscription_plans.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.id
     *
     * @param id the value for subscription_plans.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.name
     *
     * @return the value of subscription_plans.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.name
     *
     * @param name the value for subscription_plans.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.price_monthly
     *
     * @return the value of subscription_plans.price_monthly
     *
     * @mbg.generated
     */
    public BigDecimal getPriceMonthly() {
        return priceMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.price_monthly
     *
     * @param priceMonthly the value for subscription_plans.price_monthly
     *
     * @mbg.generated
     */
    public void setPriceMonthly(BigDecimal priceMonthly) {
        this.priceMonthly = priceMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.task_limit
     *
     * @return the value of subscription_plans.task_limit
     *
     * @mbg.generated
     */
    public Integer getTaskLimit() {
        return taskLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.task_limit
     *
     * @param taskLimit the value for subscription_plans.task_limit
     *
     * @mbg.generated
     */
    public void setTaskLimit(Integer taskLimit) {
        this.taskLimit = taskLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.description
     *
     * @return the value of subscription_plans.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.description
     *
     * @param description the value for subscription_plans.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_plans.created_at
     *
     * @return the value of subscription_plans.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_plans.created_at
     *
     * @param createdAt the value for subscription_plans.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}