package com.aitaskmanager.repository.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   契約情報
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table subscriptions
 */
public class Subscriptions {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriptions.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriptions.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   プランID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriptions.plan_id
     *
     * @mbg.generated
     */
    private Integer planId;

    /**
     * Database Column Remarks:
     *   状態
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriptions.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   開始時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriptions.started_at
     *
     * @mbg.generated
     */
    private Date startedAt;

    /**
     * Database Column Remarks:
     *   経過時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriptions.expires_at
     *
     * @mbg.generated
     */
    private Date expiresAt;

    /**
     * Database Column Remarks:
     *   更新時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriptions.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriptions.id
     *
     * @return the value of subscriptions.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriptions.id
     *
     * @param id the value for subscriptions.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriptions.user_id
     *
     * @return the value of subscriptions.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriptions.user_id
     *
     * @param userId the value for subscriptions.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriptions.plan_id
     *
     * @return the value of subscriptions.plan_id
     *
     * @mbg.generated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriptions.plan_id
     *
     * @param planId the value for subscriptions.plan_id
     *
     * @mbg.generated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriptions.status
     *
     * @return the value of subscriptions.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriptions.status
     *
     * @param status the value for subscriptions.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriptions.started_at
     *
     * @return the value of subscriptions.started_at
     *
     * @mbg.generated
     */
    public Date getStartedAt() {
        return startedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriptions.started_at
     *
     * @param startedAt the value for subscriptions.started_at
     *
     * @mbg.generated
     */
    public void setStartedAt(Date startedAt) {
        this.startedAt = startedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriptions.expires_at
     *
     * @return the value of subscriptions.expires_at
     *
     * @mbg.generated
     */
    public Date getExpiresAt() {
        return expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriptions.expires_at
     *
     * @param expiresAt the value for subscriptions.expires_at
     *
     * @mbg.generated
     */
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriptions.updated_at
     *
     * @return the value of subscriptions.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriptions.updated_at
     *
     * @param updatedAt the value for subscriptions.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}