package com.aitaskmanager.repository.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   タスク情報
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tasks
 */
public class Tasks {
    /**
     * Database Column Remarks:
     *   タスクSID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_sid
     *
     * @mbg.generated
     */
    private Integer taskSid;

    /**
     * Database Column Remarks:
     *   ユーザSID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.user_sid
     *
     * @mbg.generated
     */
    private Integer userSid;

    /**
     * Database Column Remarks:
     *   親タスクSID（サブタスクの親を指す）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.parent_task_sid
     *
     * @mbg.generated
     */
    private Integer parentTaskSid;

    /**
     * Database Column Remarks:
     *   AI再分解・初回分解日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.decomposed_at
     *
     * @mbg.generated
     */
    private Date decomposedAt;

    /**
     * Database Column Remarks:
     *   タイトル
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   説明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   期日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.due_date
     *
     * @mbg.generated
     */
    private Date dueDate;

    /**
     * Database Column Remarks:
     *   優先度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.priority
     *
     * @mbg.generated
     */
    private String priority;

    /**
     * Database Column Remarks:
     *   状態
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   登録時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更新時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_sid
     *
     * @return the value of tasks.task_sid
     *
     * @mbg.generated
     */
    public Integer getTaskSid() {
        return taskSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_sid
     *
     * @param taskSid the value for tasks.task_sid
     *
     * @mbg.generated
     */
    public void setTaskSid(Integer taskSid) {
        this.taskSid = taskSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.user_sid
     *
     * @return the value of tasks.user_sid
     *
     * @mbg.generated
     */
    public Integer getUserSid() {
        return userSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.user_sid
     *
     * @param userSid the value for tasks.user_sid
     *
     * @mbg.generated
     */
    public void setUserSid(Integer userSid) {
        this.userSid = userSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.parent_task_sid
     *
     * @return the value of tasks.parent_task_sid
     *
     * @mbg.generated
     */
    public Integer getParentTaskSid() {
        return parentTaskSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.parent_task_sid
     *
     * @param parentTaskSid the value for tasks.parent_task_sid
     *
     * @mbg.generated
     */
    public void setParentTaskSid(Integer parentTaskSid) {
        this.parentTaskSid = parentTaskSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.decomposed_at
     *
     * @return the value of tasks.decomposed_at
     *
     * @mbg.generated
     */
    public Date getDecomposedAt() {
        return decomposedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.decomposed_at
     *
     * @param decomposedAt the value for tasks.decomposed_at
     *
     * @mbg.generated
     */
    public void setDecomposedAt(Date decomposedAt) {
        this.decomposedAt = decomposedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.title
     *
     * @return the value of tasks.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.title
     *
     * @param title the value for tasks.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.description
     *
     * @return the value of tasks.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.description
     *
     * @param description the value for tasks.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.due_date
     *
     * @return the value of tasks.due_date
     *
     * @mbg.generated
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.due_date
     *
     * @param dueDate the value for tasks.due_date
     *
     * @mbg.generated
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.priority
     *
     * @return the value of tasks.priority
     *
     * @mbg.generated
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.priority
     *
     * @param priority the value for tasks.priority
     *
     * @mbg.generated
     */
    public void setPriority(String priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.status
     *
     * @return the value of tasks.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.status
     *
     * @param status the value for tasks.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.created_at
     *
     * @return the value of tasks.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.created_at
     *
     * @param createdAt the value for tasks.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.updated_at
     *
     * @return the value of tasks.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.updated_at
     *
     * @param updatedAt the value for tasks.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}