package com.aitaskmanager.repository.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   タスク情報
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tasks
 */
public class Tasks {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   親タスクID（サブタスクの親を指す）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.parent_task_id
     *
     * @mbg.generated
     */
    private Integer parentTaskId;

    /**
     * Database Column Remarks:
     *   AI再分解・初回分解日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.decomposed_at
     *
     * @mbg.generated
     */
    private Date decomposedAt;

    /**
     * Database Column Remarks:
     *   タイトル
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   契約
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   期日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.due_date
     *
     * @mbg.generated
     */
    private Date dueDate;

    /**
     * Database Column Remarks:
     *   優先度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.priority
     *
     * @mbg.generated
     */
    private String priority;

    /**
     * Database Column Remarks:
     *   状態
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   登録時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更新時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.id
     *
     * @return the value of tasks.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.id
     *
     * @param id the value for tasks.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.user_id
     *
     * @return the value of tasks.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.user_id
     *
     * @param userId the value for tasks.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.parent_task_id
     *
     * @return the value of tasks.parent_task_id
     *
     * @mbg.generated
     */
    public Integer getParentTaskId() {
        return parentTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.parent_task_id
     *
     * @param parentTaskId the value for tasks.parent_task_id
     *
     * @mbg.generated
     */
    public void setParentTaskId(Integer parentTaskId) {
        this.parentTaskId = parentTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.decomposed_at
     *
     * @return the value of tasks.decomposed_at
     *
     * @mbg.generated
     */
    public Date getDecomposedAt() {
        return decomposedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.decomposed_at
     *
     * @param decomposedAt the value for tasks.decomposed_at
     *
     * @mbg.generated
     */
    public void setDecomposedAt(Date decomposedAt) {
        this.decomposedAt = decomposedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.title
     *
     * @return the value of tasks.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.title
     *
     * @param title the value for tasks.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.description
     *
     * @return the value of tasks.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.description
     *
     * @param description the value for tasks.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.due_date
     *
     * @return the value of tasks.due_date
     *
     * @mbg.generated
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.due_date
     *
     * @param dueDate the value for tasks.due_date
     *
     * @mbg.generated
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.priority
     *
     * @return the value of tasks.priority
     *
     * @mbg.generated
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.priority
     *
     * @param priority the value for tasks.priority
     *
     * @mbg.generated
     */
    public void setPriority(String priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.status
     *
     * @return the value of tasks.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.status
     *
     * @param status the value for tasks.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.created_at
     *
     * @return the value of tasks.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.created_at
     *
     * @param createdAt the value for tasks.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.updated_at
     *
     * @return the value of tasks.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.updated_at
     *
     * @param updatedAt the value for tasks.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}