package com.aitaskmanager.repository.generator;

import com.aitaskmanager.repository.model.AiUsage;
import java.util.List;

public interface AiUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_usage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_usage
     *
     * @mbg.generated
     */
    int insert(AiUsage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_usage
     *
     * @mbg.generated
     */
    AiUsage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_usage
     *
     * @mbg.generated
     */
    List<AiUsage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_usage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AiUsage row);
}