package com.aitaskmanager.repository.generator;

import com.aitaskmanager.repository.model.CreditPacks;
import java.util.List;

public interface CreditPacksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_packs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer creditPackSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_packs
     *
     * @mbg.generated
     */
    int insert(CreditPacks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_packs
     *
     * @mbg.generated
     */
    CreditPacks selectByPrimaryKey(Integer creditPackSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_packs
     *
     * @mbg.generated
     */
    List<CreditPacks> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_packs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CreditPacks row);
}