package com.aitaskmanager.repository.generator;

import com.aitaskmanager.repository.model.Payments;
import java.util.List;

public interface PaymentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer paymentSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    int insert(Payments row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    Payments selectByPrimaryKey(Integer paymentSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    List<Payments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Payments row);
}