package com.aitaskmanager.repository.generator;

import com.aitaskmanager.repository.model.RefreshTokens;
import java.util.List;

public interface RefreshTokensMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refresh_tokens
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer refreshTokenSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refresh_tokens
     *
     * @mbg.generated
     */
    int insert(RefreshTokens row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refresh_tokens
     *
     * @mbg.generated
     */
    RefreshTokens selectByPrimaryKey(Integer refreshTokenSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refresh_tokens
     *
     * @mbg.generated
     */
    List<RefreshTokens> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refresh_tokens
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RefreshTokens row);
}