package com.aitaskmanager.repository.generator;

import com.aitaskmanager.repository.model.SubscriptionPlans;
import java.util.List;

public interface SubscriptionPlansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_plans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_plans
     *
     * @mbg.generated
     */
    int insert(SubscriptionPlans row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_plans
     *
     * @mbg.generated
     */
    SubscriptionPlans selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_plans
     *
     * @mbg.generated
     */
    List<SubscriptionPlans> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_plans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SubscriptionPlans row);
}