package com.aitaskmanager.repository.generator;

import com.aitaskmanager.repository.model.Subscriptions;
import java.util.List;

public interface SubscriptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated
     */
    int insert(Subscriptions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated
     */
    Subscriptions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated
     */
    List<Subscriptions> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Subscriptions row);
}