package com.aitaskmanager.repository.generator;

import com.aitaskmanager.repository.model.Tasks;
import java.util.List;

public interface TasksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer taskSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated
     */
    int insert(Tasks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated
     */
    Tasks selectByPrimaryKey(Integer taskSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated
     */
    List<Tasks> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tasks row);
}